add_mlir_conversion_library(RustToMLIRRustTypedMemoryToLLVM
  RustTypedMemoryToLLVM.cpp

  DEPENDS
  RustToMLIRRustTypedMemoryToLLVMPassIncGen
)
target_link_libraries(RustToMLIRRustTypedMemoryToLLVM
  PUBLIC
  RustToMLIRRustMIRDialect
)
mlir_target_link_libraries(RustToMLIRRustTypedMemoryToLLVM
  PUBLIC
  MLIRFuncDialect
  MLIRFuncTransforms
  MLIRIR
  MLIRLLVMDialect
  MLIRPass
  MLIRSupport
  MLIRTransformUtils
)
