add_mlir_conversion_library(RustToMLIRRustTypedToArith
  RustTypedToArith.cpp

  DEPENDS
  RustToMLIRRustTypedToArithPassIncGen
)
target_link_libraries(RustToMLIRRustTypedToArith
  PUBLIC
  RustToMLIRRustMIRDialect
)
mlir_target_link_libraries(RustToMLIRRustTypedToArith
  PUBLIC
  MLIRArithDialect
  MLIRControlFlowDialect
  MLIRDataLayoutInterfaces
  MLIRIR
  MLIRLLVMDialect
  MLIRMathDialect
  MLIRPass
  MLIRSupport
  MLIRTransformUtils
  MLIRUBDialect
)
