set(LLVM_LINK_COMPONENTS
  Support
)

add_mlir_tool(rust-opt
  rust-opt.cpp
)
llvm_update_compile_flags(rust-opt)
target_link_libraries(rust-opt
  PRIVATE
  RustToLLVMRustMIRDialect
  RustToLLVMRustMIRTransforms
  RustToLLVMRustTypedToArith
  RustToLLVMRustTypedToControlFlow
  RustToLLVMRustTypedToFunc
  RustToLLVMRustTypedMemoryToLLVM
  MLIRArithDialect
  MLIRControlFlowDialect
  MLIRDLTIDialect
  MLIRFuncDialect
  MLIRLLVMDialect
  MLIRTransforms
  MLIRUBDialect
  MLIRIR
  MLIRMlirOptMain
  MLIRPass
  MLIRSupport
  LLVMSupport
)

mlir_check_link_libraries(rust-opt)
